repo: 'section'
canvasCourse: 'web-dev-2'

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - css-order-type-main
  - img-flex
  - typografier

html:
  - path: 'index.html'
    search:
      - 'Venus'
      - 'A real-colour image of Venus.'
      - 'Venus, the second planet in the Solar System.'
      - 'Venus orbits the Sun every 224.7 Earth days.'
      - 'Physical characteristics'
      - 'Orbital Characteristics'
      - 'Surface gravity'
      - 'Orbital period'
      - 'italic'
      - 'text-'
      - 'wrapper|max-length'

css:
  - path: 'css/main.css'
    locked: true

screenshots:
  - path: 'index.html'
    sizes: [608, 960, 1440]
